// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr1n8xUyMn0TAHSz2ASd-lNO8lrDHTz_4',
    appId: '1:170017316040:ios:49829fcba3995800b999fd',
    messagingSenderId: '170017316040',
    projectId: 'fitmind-dcfcf',
    storageBucket: 'fitmind-dcfcf.firebasestorage.app',
    iosBundleId: 'com.example.fitmind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBa-gMigDuh012pQueGvUrx9bdCPoxH9k',
    appId: '1:170017316040:web:90b01d54558eea9ab999fd',
    messagingSenderId: '170017316040',
    projectId: 'fitmind-dcfcf',
    authDomain: 'fitmind-dcfcf.firebaseapp.com',
    storageBucket: 'fitmind-dcfcf.firebasestorage.app',
    measurementId: 'G-PC4L572D16',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBa-gMigDuh012pQueGvUrx9bdCPoxH9k',
    appId: '1:170017316040:web:90b01d54558eea9ab999fd',
    messagingSenderId: '170017316040',
    projectId: 'fitmind-dcfcf',
    authDomain: 'fitmind-dcfcf.firebaseapp.com',
    storageBucket: 'fitmind-dcfcf.firebasestorage.app',
    measurementId: 'G-PC4L572D16',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr1n8xUyMn0TAHSz2ASd-lNO8lrDHTz_4',
    appId: '1:170017316040:ios:49829fcba3995800b999fd',
    messagingSenderId: '170017316040',
    projectId: 'fitmind-dcfcf',
    storageBucket: 'fitmind-dcfcf.firebasestorage.app',
    iosBundleId: 'com.example.fitmind',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE7IpUdAi5_1nrZM9xq_-V-mJAUy3ZGjk',
    appId: '1:170017316040:android:2c754b95e4eb7e81b999fd',
    messagingSenderId: '170017316040',
    projectId: 'fitmind-dcfcf',
    storageBucket: 'fitmind-dcfcf.firebasestorage.app',
  );

}